sonar.projectKey=python-basic-project 
sonar.projectName="Python Basic Project" 
sonar.projectVersion=1.0 
sonar.sources=. 
sonar.sourceEncoding=UTF-8 
sonar.host.url=http://20.39.138.151:9000 
sonar.login=sqp_8c650eec3c5097611cbeb6495e9fa34588bc676b
